// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Core.Interfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Infrastructure.Data
{
    public partial class Person: IEntity
    {
        public Person()
        {
            Phones = new HashSet<Phone>();
            RelationRelatedPerson1s = new HashSet<Relation>();
            RelationRelatedPerson2s = new HashSet<Relation>();
        }
        [Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte Sex { get; set; }
        public string IdNumber { get; set; }
        public DateTime BirthDate { get; set; }
        public int SettlementId { get; set; }
        public string PictureAddress { get; set; }

        public virtual ICollection<Phone> Phones { get; set; }
        [JsonIgnore]
        public virtual ICollection<Relation> RelationRelatedPerson1s { get; set; }
        [JsonIgnore]
        public virtual ICollection<Relation> RelationRelatedPerson2s { get; set; }

        [NotMapped]
        public IEnumerable<Relation> Relations { get; set; }
    }
}