// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infrastructure.Data
{
    public partial class Phone
    {

        public string Number { get; set; }
        [JsonIgnore]
        public int PersonId { get; set; }
        public byte PhoneType { get; set; }
        [JsonIgnore]
        public virtual Person Person { get; set; }
    }
}