// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infrastructure.Data
{
    public partial class Relation
    {
        [JsonIgnore]
        public int Id { get; set; }
        public byte RelationType { get; set; }
        public int RelatedPerson1Id { get; set; }
        public int RelatedPerson2Id { get; set; }
        [JsonIgnore]
        public virtual Person RelatedPerson1 { get; set; }
        [JsonIgnore]
        public virtual Person RelatedPerson2 { get; set; }
    }
}