// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Infrastructure.Data.Data
{
    public partial class Testapp2Context : DbContext
    {
        public Testapp2Context()
        {
        }

        public Testapp2Context(DbContextOptions<Testapp2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Relation> Relations { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>(entity =>
            {
                entity.Property(e => e.BirthDate).HasColumnType("date");

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.IdNumber)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PictureAddress).HasMaxLength(200);
            });

            modelBuilder.Entity<Phone>(entity =>
            {
                entity.HasKey(e => e.Number);

                entity.Property(e => e.Number)
                    .HasColumnName("Number")
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Person)
                    .WithMany(p => p.Phones)
                    .HasForeignKey(d => d.PersonId)
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_Phones_Persons");
            });

            modelBuilder.Entity<Relation>(entity =>
            {
                entity.HasOne(d => d.RelatedPerson1)
                    .WithMany(p => p.RelationRelatedPerson1s)
                    .HasForeignKey(d => d.RelatedPerson1Id)
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_Relations_Persons");

                entity.HasOne(d => d.RelatedPerson2)
                    .WithMany(p => p.RelationRelatedPerson2s)
                    .HasForeignKey(d => d.RelatedPerson2Id)
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("FK_Relations_Persons1");
            });

            modelBuilder.Entity<Settlement>(entity =>
            {
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}